### ISSUE TITLE
org.springframework.cache.support.NullValue cannot be cast to com.*.*VO

### ISSUE THREAD

**Issue by nimbusking** [nimbusking/itopener-parent#2]
redis+caffeine二级缓存组合中，如果当在降级查询时返回为空的场景时，会遇到上述类型转化错
当开启sync=true时：
`@Cacheable(key = "'cache_user_id_' + #id", value = "userIdCache", cacheManager = "cacheManager", sync = true)
	public UserVO getForNull(long id) {
		logger.info("get by name from db, but return null");
		return null;
	}`

错误日志：
`
java.lang.ClassCastException: org.springframework.cache.support.NullValue cannot be cast to com.itopener.demo.cache.redis.caffeine.vo.UserVO
	at com.itopener.demo.cache.redis.caffeine.service.CacheRedisCaffeineService$$EnhancerBySpringCGLIB$$1.getForNull(<generated>)
	at com.itopener.demo.cache.redis.caffeine.controller.CacheRedisCaffeineController.getByNull(CacheRedisCaffeineController.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
`

**Comment by nimbusking** [comment]
从`get(Object key, Callable<T> valueLoader)`方法中，增加NullValue类型判断，如果是NullValue则返回null
