### ISSUE TITLE
Caffeine存入null时空指针异常

### ISSUE THREAD

**Issue by nimbusking** [nimbusking/itopener-parent#4]
涉及代码，当默认没有开启sync=true时

`caffeineCache.put(key, value);`

`
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.putFast(BoundedLocalCache.java:1511)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:1474)
	at com.github.benmanes.caffeine.cache.LocalManualCache.put(LocalManualCache.java:64)
	at com.itopener.cache.redis.caffeine.spring.boot.autoconfigure.support.RedisCaffeineCache.put(RedisCaffeineCache.java:124)
`

**Comment by nimbusking** [comment]
问题原因在Caffeine不支持存入null值，详见： [What should be the effect of returning a null pointer from a cache callback](https://github.com/ben-manes/caffeine/issues/31)

**Comment by nimbusking** [comment]
merge and close
